baseURL = "https://topsee.top"
languageCode = "zh-cn"
title = "悲酥清风﹌"
theme = "LeaveIt"
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字

paginate = 12 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "" # Google 统计 id

preserveTaxonomyNames = true
# toc = true #文章导航

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博文"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "归档"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    since = 2018
    author = "悲酥清风﹌"                           # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "时间在哪儿，成就就在哪儿。"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "czy8187"
    # Twitter = "xxoo"
    Email   = "a.czy@qq.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

